"""
Core/engine/pdf_builder.py

Modern PDF report builder — extracted from legacy Core/PDF_Converter.py.
Generates HTML report strings from templates without interactive prompts
or external dependencies (pdfkit/BeautifulSoup handled by callers).

Phase-out Phase 1 — PDFBuilder replaces Core.PDF_Converter.Menu.
"""
from __future__ import annotations

import os
from datetime import datetime

from Core.Support import DateFormat

_logger = None


def _logger():
    """Lazy logger để tránh module-level I/O side effects."""
    global _logger
    if _logger is None:
        from Core.config.logging_config import get_logger
        _logger = get_logger(__name__)
    return _logger


class PDFBuilder:
    """
    PDF report builder utilities.

    Replaces legacy Core.PDF_Converter.Menu.
    """

    TEMPLATES = {
        1: {"name": "LIGHT", "css": "../../Css/Light/Pdf.css"},
        2: {"name": "DARK", "css": "../../Css/Dark/Pdf.css"},
        3: {"name": "HIGH-CONTRAST", "css": "../../Css/High-Contrast/Pdf.css"},
    }

    @staticmethod
    def get_template_name(template_num: int) -> str:
        """Get template name by number.

        Args:
            template_num: Template number (1-3).

        Returns:
            Template name string. Defaults to LIGHT if unknown.
        """
        return PDFBuilder.TEMPLATES.get(
            template_num, PDFBuilder.TEMPLATES[1])["name"]

    @staticmethod
    def get_template_css(template_num: int) -> str:
        """Get template CSS path by number.

        Args:
            template_num: Template number (1-3).

        Returns:
            CSS path string. Defaults to LIGHT if unknown.
        """
        return PDFBuilder.TEMPLATES.get(
            template_num, PDFBuilder.TEMPLATES[1])["css"]

    @staticmethod
    def generate_html(
        username: str,
        content: str,
        template: int = 1,
    ) -> str:
        """Generate HTML report string.

        Args:
            username: Target username for the report.
            content: Report content to embed.
            template: Template number (1=LIGHT, 2=DARK, 3=HIGH-CONTRAST).

        Returns:
            Complete HTML document string.
        """
        now = datetime.now()
        dataformat = DateFormat.Get.Format()
        dt_string = now.strftime(dataformat)
        date = str(dt_string)
        style = '<link rel = "stylesheet" href= "{}">'.format(
            PDFBuilder.get_template_css(template))
        normalized_content = (
            str(content)
            .replace("../Reports", "GUI/Reports")
            .replace("../Icon", "GUI/Icon")
            .replace("\n", "")
            .replace("''", "")
        )
        header = '''<html>
        <head>
        {}
        <meta charset = "utf-8">
        </head>
        <body>
         <p>PDF REPORT FOR {} GRAPH</p>
          <div class = "Metadata">
            <p id = "Bold">METADATA:</p>
            <p>PDF GENERATED BY MR.HOLMES</p>
            <p>GENERATED ON: {}</p>
            <p>MR.HOLMES DOWNLOAD LINK: https//github.com/Lucksi/Mr.Holmes</p>
           </div>
            <br>
            {}
        </body>
        </html>'''.format(style, username, date, normalized_content)
        return header
